# I2C Bus URI used to comunicate with I2C devices (default: "/dev/i2c-1")
bus_uri: "/dev/i2c-1"

# I2C address of MPU6050 (default: 0x68)
mpu_address: 0x68

# Frequency in Hertz wich IMU data is published (default: 30)
pub_rate: 200

# Frame if of IMU message (default: "imu")
frame_id: "imu"

# Offsets to fix wrong values caused by misalignment
# Sequence is (ax, ay, az, gx, gy, gz) (default: [0, 0, 0, 0, 0, 0])
axes_offsets: [-2808, 2408, 3420, 126, -18, 43]

# PID constants used in calibration procedure
ki: 0.2 # (default: 0.1)
kp: 0.1 # (default: 0.1)

# The calibration process is finished when the error is aproximate zero with
# the precision set by delta (default: 0.5) 
delta: 0.5


# [ INFO] [1735563609.203221757]: Parameter kp found and it value is 0.1
# [ INFO] [1735563609.203791181]: Parameter ki found and it value is 0.2
# [ INFO] [1735563609.204366106]: Parameter delta found and it value is 0.5
# [ INFO] [1735563609.205060104]: MPU6050 Calibration Node has started
# [ INFO] [1735563662.550402599]: Final offset of Accel X axis = -2808
# [ INFO] [1735563662.550448840]: Final offset of Accel Y axis = 2408
# [ INFO] [1735563662.550480766]: Final offset of Accel Z axis = 3420
# [ INFO] [1735563662.550802987]: Final offset of Gyro  X axis = 126
# [ INFO] [1735563662.550831320]: Final offset of Gyro  Y axis = -18
# [ INFO] [1735563662.550853709]: Final offset of Gyro  Z axis = 43
# [ INFO] [1735563662.550873450]: Insert these value above in the config file
